server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:

      discovery:
        locator:
          enable: true
      routes:
        - id: uecr-libro-service
          uri: lb://uecr-libro-service
          predicates:
            - Path=/libros/**
        - id: uecr-usuario-service
          uri: lb://uecr-usuario-service
          predicates:
            - Path=/usuarios/**
        - id: uecr-prestamo-service
          uri: lb://uecr-prestamo-service
          predicates:
            - Path=/prestamos/**